site_name: FlexAlloc
site_dir: public
theme:
  name: material
  palette:
    scheme: default
    primary: deep purple
  #features:
  #  - navigation.tabs
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Introduction:
    - About FlexAlloc: about.md
    - Architecture Overview: index.md
  - Blog:
    - Welcome: blog/20220201-welcome.md
  - Getting Started:
    - Installing FlexAlloc: installing-flexalloc.md
    - Example Applications: index.md
    - Using FlexAlloc from C: index.md
    - Benchmarking with Fio: index.md
    - Benchmarking with RocksDB backend: index.md
  - Contributing:
    - Code Conventions: code-conventions.md
    - Testing: testing.md